### ISSUE TITLE
(URGENT) Crashing relaton-w3c using data index

### ISSUE THREAD

**Issue by ronaldtse** [relaton/relaton-w3c#25]
```
[relaton-w3c] ("W3C TR vocab-adms") fetching...
#<Thread:0x0000000117847bd8 /Users/me/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/relaton-1.11.0/lib/relaton/workers_pool.rb:10 run> terminated with exception (report_on_exception is true):
/Users/me/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/relaton-w3c-1.11.3/lib/relaton_w3c/data_index.rb:72:in `escape': no implicit conversion of nil into String (TypeError)
	from /Users/me/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/relaton-w3c-1.11.3/lib/relaton_w3c/data_index.rb:72:in `block in search'
	from /Users/me/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/relaton-w3c-1.11.3/lib/relaton_w3c/data_index.rb:71:in `each'
	from /Users/me/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/relaton-w3c-1.11.3/lib/relaton_w3c/data_index.rb:71:in `detect'
	from /Users/me/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/relaton-w3c-1.11.3/lib/relaton_w3c/data_index.rb:71:in `search'
	from /Users/me/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/relaton-w3c-1.11.3/lib/relaton_w3c/w3c_bibliography.rb:15:in `search'
	from /Users/me/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/relaton-w3c-1.11.3/lib/relaton_w3c/w3c_bibliography.rb:38:in `get'
	from /Users/me/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/relaton-w3c-1.11.3/lib/relaton_w3c/processor.rb:20:in `get'
	from /Users/me/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/relaton-1.11.0/lib/relaton/db.rb:432:in `net_retry'
	from /Users/me/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/relaton-1.11.0/lib/relaton/db.rb:417:in `new_bib_entry'
	from /Users/me/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/relaton-1.11.0/lib/relaton/db.rb:397:in `check_bibliocache'
	from /Users/me/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/relaton-1.11.0/lib/relaton/db.rb:74:in `fetch'
	from /Users/me/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/relaton-1.11.0/lib/relaton/db.rb:110:in `block in fetch_async'
	from /Users/me/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/relaton-1.11.0/lib/relaton/workers_pool.rb:11:in `block (2 levels) in initialize'
#<Thread:0x0000000117846008 /Users/me/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/relaton-1.11.0/lib/relaton/workers_pool.rb:10 run> terminated with exception (report_on_exception is true):
/Users/me/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/relaton-w3c-1.11.3/lib/relaton_w3c/data_index.rb:72:in `escape': no implicit conversion of nil into String (TypeError)
	from /Users/me/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/relaton-w3c-1.11.3/lib/relaton_w3c/data_index.rb:72:in `block in search'
	from /Users/me/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/relaton-w3c-1.11.3/lib/relaton_w3c/data_index.rb:71:in `each'
	from /Users/me/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/relaton-w3c-1.11.3/lib/relaton_w3c/data_index.rb:71:in `detect'
	from /Users/me/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/relaton-w3c-1.11.3/lib/relaton_w3c/data_index.rb:71:in `search'
	from /Users/me/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/relaton-w3c-1.11.3/lib/relaton_w3c/w3c_bibliography.rb:15:in `search'
	from /Users/me/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/relaton-w3c-1.11.3/lib/relaton_w3c/w3c_bibliography.rb:38:in `get'
	from /Users/me/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/relaton-w3c-1.11.3/lib/relaton_w3c/processor.rb:20:in `get'
	from /Users/me/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/relaton-1.11.0/lib/relaton/db.rb:432:in `net_retry'
	from /Users/me/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/relaton-1.11.0/lib/relaton/db.rb:417:in `new_bib_entry'
	from /Users/me/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/relaton-1.11.0/lib/relaton/db.rb:397:in `check_bibliocache'
	from /Users/me/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/relaton-1.11.0/lib/relaton/db.rb:74:in `fetch'
	from /Users/me/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/relaton-1.11.0/lib/relaton/db.rb:110:in `block in fetch_async'
	from /Users/me/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/relaton-1.11.0/lib/relaton/workers_pool.rb:11:in `block (2 levels) in initialize'
#<Thread:0x0000000117847f48 /Users/me/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/relaton-1.11.0/lib/relaton/workers_pool.rb:10 run> terminated with exception (report_on_exception is true):
/Users/me/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/relaton-w3c-1.11.3/lib/relaton_w3c/data_index.rb:72:in `escape': no implicit conversion of nil into String (TypeError)
	from /Users/me/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/relaton-w3c-1.11.3/lib/relaton_w3c/data_index.rb:72:in `block in search'
	from /Users/me/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/relaton-w3c-1.11.3/lib/relaton_w3c/data_index.rb:71:in `each'
	from /Users/me/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/relaton-w3c-1.11.3/lib/relaton_w3c/data_index.rb:71:in `detect'
	from /Users/me/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/relaton-w3c-1.11.3/lib/relaton_w3c/data_index.rb:71:in `search'
	from /Users/me/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/relaton-w3c-1.11.3/lib/relaton_w3c/w3c_bibliography.rb:15:in `search'
	from /Users/me/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/relaton-w3c-1.11.3/lib/relaton_w3c/w3c_bibliography.rb:38:in `get'
	from /Users/me/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/relaton-w3c-1.11.3/lib/relaton_w3c/processor.rb:20:in `get'
	from /Users/me/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/relaton-1.11.0/lib/relaton/db.rb:432:in `net_retry'
	from /Users/me/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/relaton-1.11.0/lib/relaton/db.rb:417:in `new_bib_entry'
	from /Users/me/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/relaton-1.11.0/lib/relaton/db.rb:397:in `check_bibliocache'
	from /Users/me/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/relaton-1.11.0/lib/relaton/db.rb:74:in `fetch'
	from /Users/me/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/relaton-1.11.0/lib/relaton/db.rb:110:in `block in fetch_async'
	from /Users/me/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/relaton-1.11.0/lib/relaton/workers_pool.rb:11:in `block (2 levels) in initialize'
#<Thread:0x000000011784d380 /Users/me/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/relaton-1.11.0/lib/relaton/workers_pool.rb:10 run> terminated with exception (report_on_exception is true):
/Users/me/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/relaton-w3c-1.11.3/lib/relaton_w3c/data_index.rb:72:in `escape': no implicit conversion of nil into String (TypeError)
	from /Users/me/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/relaton-w3c-1.11.3/lib/relaton_w3c/data_index.rb:72:in `block in search'
	from /Users/me/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/relaton-w3c-1.11.3/lib/relaton_w3c/data_index.rb:71:in `each'
	from /Users/me/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/relaton-w3c-1.11.3/lib/relaton_w3c/data_index.rb:71:in `detect'
	from /Users/me/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/relaton-w3c-1.11.3/lib/relaton_w3c/data_index.rb:71:in `search'
	from /Users/me/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/relaton-w3c-1.11.3/lib/relaton_w3c/w3c_bibliography.rb:15:in `search'
	from /Users/me/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/relaton-w3c-1.11.3/lib/relaton_w3c/w3c_bibliography.rb:38:in `get'
	from /Users/me/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/relaton-w3c-1.11.3/lib/relaton_w3c/processor.rb:20:in `get'
	from /Users/me/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/relaton-1.11.0/lib/relaton/db.rb:432:in `net_retry'
	from /Users/me/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/relaton-1.11.0/lib/relaton/db.rb:417:in `new_bib_entry'
	from /Users/me/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/relaton-1.11.0/lib/relaton/db.rb:397:in `check_bibliocache'
	from /Users/me/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/relaton-1.11.0/lib/relaton/db.rb:74:in `fetch'
	from /Users/me/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/relaton-1.11.0/lib/relaton/db.rb:110:in `block in fetch_async'
	from /Users/me/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/relaton-1.11.0/lib/relaton/workers_pool.rb:11:in `block (2 levels) in initialize'
#<Thread:0x000000011784c200 /Users/me/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/relaton-1.11.0/lib/relaton/workers_pool.rb:10 run> terminated with exception (report_on_exception is true):
/Users/me/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/relaton-w3c-1.11.3/lib/relaton_w3c/data_index.rb:72:in `escape': no implicit conversion of nil into String (TypeError)
	from /Users/me/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/relaton-w3c-1.11.3/lib/relaton_w3c/data_index.rb:72:in `block in search'
	from /Users/me/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/relaton-w3c-1.11.3/lib/relaton_w3c/data_index.rb:71:in `each'
	from /Users/me/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/relaton-w3c-1.11.3/lib/relaton_w3c/data_index.rb:71:in `detect'
	from /Users/me/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/relaton-w3c-1.11.3/lib/relaton_w3c/data_index.rb:71:in `search'
	from /Users/me/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/relaton-w3c-1.11.3/lib/relaton_w3c/w3c_bibliography.rb:15:in `search'
	from /Users/me/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/relaton-w3c-1.11.3/lib/relaton_w3c/w3c_bibliography.rb:38:in `get'
	from /Users/me/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/relaton-w3c-1.11.3/lib/relaton_w3c/processor.rb:20:in `get'
	from /Users/me/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/relaton-1.11.0/lib/relaton/db.rb:432:in `net_retry'
	from /Users/me/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/relaton-1.11.0/lib/relaton/db.rb:417:in `new_bib_entry'
	from /Users/me/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/relaton-1.11.0/lib/relaton/db.rb:397:in `check_bibliocache'
	from /Users/me/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/relaton-1.11.0/lib/relaton/db.rb:74:in `fetch'
	from /Users/me/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/relaton-1.11.0/lib/relaton/db.rb:110:in `block in fetch_async'
	from /Users/me/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/relaton-1.11.0/lib/relaton/workers_pool.rb:11:in `block (2 levels) in initialize'
#<Thread:0x00000001178459a0 /Users/me/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/relaton-1.11.0/lib/relaton/workers_pool.rb:10 run> terminated with exception (report_on_exception is true):
/Users/me/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/relaton-w3c-1.11.3/lib/relaton_w3c/data_index.rb:72:in `escape': no implicit conversion of nil into String (TypeError)
	from /Users/me/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/relaton-w3c-1.11.3/lib/relaton_w3c/data_index.rb:72:in `block in search'
	from /Users/me/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/relaton-w3c-1.11.3/lib/relaton_w3c/data_index.rb:71:in `each'
	from /Users/me/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/relaton-w3c-1.11.3/lib/relaton_w3c/data_index.rb:71:in `detect'
	from /Users/me/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/relaton-w3c-1.11.3/lib/relaton_w3c/data_index.rb:71:in `search'
	from /Users/me/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/relaton-w3c-1.11.3/lib/relaton_w3c/w3c_bibliography.rb:15:in `search'
	from /Users/me/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/relaton-w3c-1.11.3/lib/relaton_w3c/w3c_bibliography.rb:38:in `get'
	from /Users/me/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/relaton-w3c-1.11.3/lib/relaton_w3c/processor.rb:20:in `get'
	from /Users/me/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/relaton-1.11.0/lib/relaton/db.rb:432:in `net_retry'
	from /Users/me/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/relaton-1.11.0/lib/relaton/db.rb:417:in `new_bib_entry'
	from /Users/me/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/relaton-1.11.0/lib/relaton/db.rb:397:in `check_bibliocache'
	from /Users/me/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/relaton-1.11.0/lib/relaton/db.rb:74:in `fetch'
	from /Users/me/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/relaton-1.11.0/lib/relaton/db.rb:110:in `block in fetch_async'
	from /Users/me/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/relaton-1.11.0/lib/relaton/workers_pool.rb:11:in `block (2 levels) in initialize'
#<Thread:0x00000001178470e8 /Users/me/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/relaton-1.11.0/lib/relaton/workers_pool.rb:10 run> terminated with exception (report_on_exception is true):
/Users/me/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/relaton-w3c-1.11.3/lib/relaton_w3c/data_index.rb:72:in `escape': no implicit conversion of nil into String (TypeError)
	from /Users/me/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/relaton-w3c-1.11.3/lib/relaton_w3c/data_index.rb:72:in `block in search'
	from /Users/me/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/relaton-w3c-1.11.3/lib/relaton_w3c/data_index.rb:71:in `each'
	from /Users/me/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/relaton-w3c-1.11.3/lib/relaton_w3c/data_index.rb:71:in `detect'
	from /Users/me/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/relaton-w3c-1.11.3/lib/relaton_w3c/data_index.rb:71:in `search'
	from /Users/me/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/relaton-w3c-1.11.3/lib/relaton_w3c/w3c_bibliography.rb:15:in `search'
	from /Users/me/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/relaton-w3c-1.11.3/lib/relaton_w3c/w3c_bibliography.rb:38:in `get'
	from /Users/me/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/relaton-w3c-1.11.3/lib/relaton_w3c/processor.rb:20:in `get'
	from /Users/me/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/relaton-1.11.0/lib/relaton/db.rb:432:in `net_retry'
	from /Users/me/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/relaton-1.11.0/lib/relaton/db.rb:417:in `new_bib_entry'
	from /Users/me/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/relaton-1.11.0/lib/relaton/db.rb:397:in `check_bibliocache'
	from /Users/me/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/relaton-1.11.0/lib/relaton/db.rb:74:in `fetch'
	from /Users/me/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/relaton-1.11.0/lib/relaton/db.rb:110:in `block in fetch_async'
	from /Users/me/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/relaton-1.11.0/lib/relaton/workers_pool.rb:11:in `block (2 levels) in initialize'
[relaton-ogc] WARNING: no match found online for OGC 20-072r2. The code must be exactly like it is on the standards website.
[relaton-oasis] (OASIS CIQ v3.0) not found
[relaton-ogc] ("OGC 04-100") found 04-100
#<Thread:0x00000001178469b8 /Users/me/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/relaton-1.11.0/lib/relaton/workers_pool.rb:10 run> terminated with exception (report_on_exception is true):
/Users/me/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/relaton-w3c-1.11.3/lib/relaton_w3c/data_index.rb:72:in `escape': no implicit conversion of nil into String (TypeError)
	from /Users/me/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/relaton-w3c-1.11.3/lib/relaton_w3c/data_index.rb:72:in `block in search'
	from /Users/me/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/relaton-w3c-1.11.3/lib/relaton_w3c/data_index.rb:71:in `each'
	from /Users/me/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/relaton-w3c-1.11.3/lib/relaton_w3c/data_index.rb:71:in `detect'
	from /Users/me/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/relaton-w3c-1.11.3/lib/relaton_w3c/data_index.rb:71:in `search'
	from /Users/me/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/relaton-w3c-1.11.3/lib/relaton_w3c/w3c_bibliography.rb:15:in `search'
	from /Users/me/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/relaton-w3c-1.11.3/lib/relaton_w3c/w3c_bibliography.rb:38:in `get'
	from /Users/me/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/relaton-w3c-1.11.3/lib/relaton_w3c/processor.rb:20:in `get'
	from /Users/me/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/relaton-1.11.0/lib/relaton/db.rb:432:in `net_retry'
	from /Users/me/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/relaton-1.11.0/lib/relaton/db.rb:417:in `new_bib_entry'
	from /Users/me/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/relaton-1.11.0/lib/relaton/db.rb:397:in `check_bibliocache'
	from /Users/me/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/relaton-1.11.0/lib/relaton/db.rb:74:in `fetch'
	from /Users/me/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/relaton-1.11.0/lib/relaton/db.rb:110:in `block in fetch_async'
	from /Users/me/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/relaton-1.11.0/lib/relaton/workers_pool.rb:11:in `block (2 levels) in initialize'
[relaton-ogc] WARNING: no match found online for OGC 20-040r3. The code must be exactly like it is on the standards website.
#<Thread:0x0000000117846260 /Users/me/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/relaton-1.11.0/lib/relaton/workers_pool.rb:10 run> terminated with exception (report_on_exception is true):
/Users/me/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/relaton-w3c-1.11.3/lib/relaton_w3c/data_index.rb:72:in `escape': no implicit conversion of nil into String (TypeError)
	from /Users/me/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/relaton-w3c-1.11.3/lib/relaton_w3c/data_index.rb:72:in `block in search'
	from /Users/me/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/relaton-w3c-1.11.3/lib/relaton_w3c/data_index.rb:71:in `each'
	from /Users/me/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/relaton-w3c-1.11.3/lib/relaton_w3c/data_index.rb:71:in `detect'
	from /Users/me/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/relaton-w3c-1.11.3/lib/relaton_w3c/data_index.rb:71:in `search'
	from /Users/me/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/relaton-w3c-1.11.3/lib/relaton_w3c/w3c_bibliography.rb:15:in `search'
	from /Users/me/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/relaton-w3c-1.11.3/lib/relaton_w3c/w3c_bibliography.rb:38:in `get'
	from /Users/me/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/relaton-w3c-1.11.3/lib/relaton_w3c/processor.rb:20:in `get'
	from /Users/me/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/relaton-1.11.0/lib/relaton/db.rb:432:in `net_retry'
	from /Users/me/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/relaton-1.11.0/lib/relaton/db.rb:417:in `new_bib_entry'
	from /Users/me/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/relaton-1.11.0/lib/relaton/db.rb:397:in `check_bibliocache'
	from /Users/me/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/relaton-1.11.0/lib/relaton/db.rb:74:in `fetch'
	from /Users/me/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/relaton-1.11.0/lib/relaton/db.rb:110:in `block in fetch_async'
	from /Users/me/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/relaton-1.11.0/lib/relaton/workers_pool.rb:11:in `block (2 levels) in initialize'
[relaton-ogc] WARNING: no match found online for OGC 20-010. The code must be exactly like it is on the standards website.
#<Thread:0x0000000117844ff0 /Users/me/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/relaton-1.11.0/lib/relaton/workers_pool.rb:10 run> terminated with exception (report_on_exception is true):
/Users/me/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/relaton-w3c-1.11.3/lib/relaton_w3c/data_index.rb:72:in `escape': no implicit conversion of nil into String (TypeError)
	from /Users/me/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/relaton-w3c-1.11.3/lib/relaton_w3c/data_index.rb:72:in `block in search'
	from /Users/me/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/relaton-w3c-1.11.3/lib/relaton_w3c/data_index.rb:71:in `each'
	from /Users/me/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/relaton-w3c-1.11.3/lib/relaton_w3c/data_index.rb:71:in `detect'
	from /Users/me/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/relaton-w3c-1.11.3/lib/relaton_w3c/data_index.rb:71:in `search'
	from /Users/me/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/relaton-w3c-1.11.3/lib/relaton_w3c/w3c_bibliography.rb:15:in `search'
	from /Users/me/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/relaton-w3c-1.11.3/lib/relaton_w3c/w3c_bibliography.rb:38:in `get'
	from /Users/me/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/relaton-w3c-1.11.3/lib/relaton_w3c/processor.rb:20:in `get'
	from /Users/me/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/relaton-1.11.0/lib/relaton/db.rb:432:in `net_retry'
	from /Users/me/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/relaton-1.11.0/lib/relaton/db.rb:417:in `new_bib_entry'
	from /Users/me/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/relaton-1.11.0/lib/relaton/db.rb:397:in `check_bibliocache'
	from /Users/me/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/relaton-1.11.0/lib/relaton/db.rb:74:in `fetch'
	from /Users/me/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/relaton-1.11.0/lib/relaton/db.rb:110:in `block in fetch_async'
	from /Users/me/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/relaton-1.11.0/lib/relaton/workers_pool.rb:11:in `block (2 levels) in initialize'
```

**Comment by ronaldtse** [comment]
Confirmed fixed.
