### ISSUE TITLE
Incompatibility with Ruby 3.2.0

### ISSUE THREAD

**Issue by opoudjis** [relaton/relaton-w3c#34]
We're about to move to Ruby 3.2.0 on Github Actions. There is an incompatibility with Ruby 3.2.0 in the RDF gem:

````
/Users/nickn/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/rdf-n3-3.1.2/lib/rdf/n3/refinements.rb:176:in `include': Refinement#include has been removed (TypeError)

    include ::RDF::Term
            ^^^^^^^^^^^
	from /Users/nickn/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/rdf-n3-3.1.2/lib/rdf/n3/refinements.rb:176:in `block in <module:Refinements>'
	from /Users/nickn/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/rdf-n3-3.1.2/lib/rdf/n3/refinements.rb:174:in `refine'
	from /Users/nickn/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/rdf-n3-3.1.2/lib/rdf/n3/refinements.rb:174:in `<module:Refinements>'
	from /Users/nickn/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/rdf-n3-3.1.2/lib/rdf/n3/refinements.rb:2:in `<top (required)>'
	from /Users/nickn/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/rdf-n3-3.1.2/lib/rdf/n3.rb:26:in `require'
	from /Users/nickn/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/rdf-n3-3.1.2/lib/rdf/n3.rb:26:in `<module:N3>'
	from /Users/nickn/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/rdf-n3-3.1.2/lib/rdf/n3.rb:21:in `<module:RDF>'
	from /Users/nickn/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/rdf-n3-3.1.2/lib/rdf/n3.rb:3:in `<top (required)>'
	from /Users/nickn/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/linkeddata-3.1.6/lib/linkeddata.rb:26:in `require'
	from /Users/nickn/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/linkeddata-3.1.6/lib/linkeddata.rb:26:in `<module:LinkedData>'
	from /Users/nickn/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/linkeddata-3.1.6/lib/linkeddata.rb:1:in `<top (required)>'
	from /Users/nickn/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/relaton-w3c-1.14.0/lib/relaton_w3c/data_fetcher.rb:2:in `require'
	from /Users/nickn/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/relaton-w3c-1.14.0/lib/relaton_w3c/data_fetcher.rb:2:in `<top (required)>'
	from /Users/nickn/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/relaton-w3c-1.14.0/lib/relaton_w3c.rb:8:in `require'
	from /Users/nickn/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/relaton-w3c-1.14.0/lib/relaton_w3c.rb:8:in `<top (required)>'
	from /Users/nickn/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/relaton-1.14.2/lib/relaton/registry.rb:28:in `require'
	from /Users/nickn/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/relaton-1.14.2/lib/relaton/registry.rb:28:in `block in register_gems'
	from /Users/nickn/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/relaton-1.14.2/lib/relaton/registry.rb:27:in `each'
	from /Users/nickn/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/relaton-1.14.2/lib/relaton/registry.rb:27:in `register_gems'
	from /Users/nickn/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/relaton-1.14.2/lib/relaton/registry.rb:21:in `initialize'
	from /Users/nickn/.rbenv/versions/3.2.0/lib/ruby/3.2.0/singleton.rb:127:in `new'
	from /Users/nickn/.rbenv/versions/3.2.0/lib/ruby/3.2.0/singleton.rb:127:in `block in instance'
	from /Users/nickn/.rbenv/versions/3.2.0/lib/ruby/3.2.0/singleton.rb:125:in `synchronize'
	from /Users/nickn/.rbenv/versions/3.2.0/lib/ruby/3.2.0/singleton.rb:125:in `instance'
	from /Users/nickn/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/relaton-1.14.2/lib/relaton/db.rb:6:in `initialize'
	from /Users/nickn/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/relaton-1.14.2/lib/relaton/db.rb:530:in `new'
	from /Users/nickn/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/relaton-1.14.2/lib/relaton/db.rb:530:in `init_bib_caches'
````

**Comment by opoudjis** [comment]
From @andrew2net 

> The rdf gem doesn't work with Ruby 3.2 yet

**Comment by andrew2net** [comment]
fixed in the last version
